### ISSUE TITLE
Peer to Peer code Review #1

### ISSUE THREAD

**Issue by saqibjavaiddev** [bienvenuushindi/sneak-peek#2]
Hi, bienvenuushindi,

You have done a great job. Congratulations on completing this project. Here I have some optional suggestions for you.

- I suggest adding some margin-top for the `h1`
- Also please if you can increase the **font-size** for the book title and author name.

Thanks

**Comment by bienvenuushindi** [comment]
Thanks, @saqibjavaiddev  I have now fixed everything
